EVO_CONFIG = {
    'POPULATION_SIZE': 200,
    'DROP_RATIO': 0.666666666,
    'MUTATION_RATE': 0.1,
    'NO_OF_MAPS': 20,
    'NO_OF_ITERATIONS': 19,
    'POOL_SIZE': 14
}

FIELD_CONFIG = {
    'DEFAULT_VALUE': 0,
    'FLOOR': 0,
    'ROCK': 1,
    'NAF': None
}

GROUP_CONFIG = {
    'NO_GROUP_ID': -1
}

MAP_CONFIG = {
    'SIZE': 100
}
