GROUP_CONSTANTS = {
    'NO_GROUP_ID': -1,
    'EXITS_RATIO': 0.1,
    }

FIELD_CONSTANTS = {
    'DEFAULT_VALUE': 0,
    'FLOOR': 0,
    'ROCK': 1,
    'WAGES': [1, 1, 1,
            1, 0, 1, 
            1, 1, 1],
    'MOORE_NEIGHBOURHOOD_SIZE': 1,
    'CONDITION': 0.5,
    'NAF': None
    }
    
MAP_CONSTANTS = {
    'SIZE': 25,
    'INITIAL_RATIO': 0.525,
    'NUMBER_OF_ITERATIONS': 1,
    'SEED': 42,
    }

MAP_CONTEXT_CONSTANTS = {
    'DEFAULT_HORIZONTAL_BOUND': [[FIELD_CONSTANTS['DEFAULT_VALUE']] * MAP_CONSTANTS['SIZE']] * FIELD_CONSTANTS['MOORE_NEIGHBOURHOOD_SIZE'],
    'DEFAULT_VERTICAL_BOUND': [[FIELD_CONSTANTS['DEFAULT_VALUE']] * FIELD_CONSTANTS['MOORE_NEIGHBOURHOOD_SIZE']] * MAP_CONSTANTS['SIZE'],
    'DEFAULT_CORNER_BOUND': [[FIELD_CONSTANTS['DEFAULT_VALUE']] * FIELD_CONSTANTS['MOORE_NEIGHBOURHOOD_SIZE']] * FIELD_CONSTANTS['MOORE_NEIGHBOURHOOD_SIZE']
    }

ROGUE_CONSTANTS = {
    'MAX_TORCH_SIZE': 5,
    'TORCH_BURN_TIME': 25
    }
