FIELD_CONSTANTS = {
    'NEIGHBOURHOOD_SIZE': 2,
    'WAGES': [[0],
              [1, 1, 1,
               1, 1,
               1, 1, 1],
              [1, 1, 1, 1,
               1, 1, 1, 1,
               1, 1, 1, 1,
               1, 1, 1, 1]],
    'CONDITION': ["> 1",
                  ">= 0.5",
                  "< 0.125"]
}

MAP_CONSTANTS = {
    'INITIAL_RATIO': 0.5,
    'NUMBER_OF_ITERATIONS': 4,
}

ROGUE_CONSTANTS = {
    'MAX_TORCH_SIZE': 5,
    'TORCH_BURN_TIME': 50
}

#
# MAP_CONTEXT_CONSTANTS = {
#     'DEFAULT_HORIZONTAL_BOUND': [[FIELD_CONSTANTS['DEFAULT_VALUE']] * MAP_CONSTANTS['SIZE']] * FIELD_CONSTANTS['NEIGHBOURHOOD_SIZE'],
#     'DEFAULT_VERTICAL_BOUND': [[FIELD_CONSTANTS['DEFAULT_VALUE']] * FIELD_CONSTANTS['NEIGHBOURHOOD_SIZE']] * MAP_CONSTANTS['SIZE'],
#     'DEFAULT_CORNER_BOUND': [[FIELD_CONSTANTS['DEFAULT_VALUE']] * FIELD_CONSTANTS['NEIGHBOURHOOD_SIZE']] * FIELD_CONSTANTS['NEIGHBOURHOOD_SIZE']
#     }
